// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/metrics_collector.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceUrl    string                 `protobuf:"bytes,1,opt,name=service_url,json=serviceUrl,proto3" json:"service_url,omitempty"`
	MetricName    string                 `protobuf:"bytes,2,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	PodName       string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	MetricValue   float64                `protobuf:"fixed64,4,opt,name=metric_value,json=metricValue,proto3" json:"metric_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMetricRequest) Reset() {
	*x = SendMetricRequest{}
	mi := &file_proto_metrics_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMetricRequest) ProtoMessage() {}

func (x *SendMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMetricRequest.ProtoReflect.Descriptor instead.
func (*SendMetricRequest) Descriptor() ([]byte, []int) {
	return file_proto_metrics_collector_proto_rawDescGZIP(), []int{0}
}

func (x *SendMetricRequest) GetServiceUrl() string {
	if x != nil {
		return x.ServiceUrl
	}
	return ""
}

func (x *SendMetricRequest) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *SendMetricRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *SendMetricRequest) GetMetricValue() float64 {
	if x != nil {
		return x.MetricValue
	}
	return 0
}

type SendMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	ServiceUrl    string                 `protobuf:"bytes,2,opt,name=service_url,json=serviceUrl,proto3" json:"service_url,omitempty"`
	MetricName    string                 `protobuf:"bytes,3,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	PodName       string                 `protobuf:"bytes,4,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMetricResponse) Reset() {
	*x = SendMetricResponse{}
	mi := &file_proto_metrics_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMetricResponse) ProtoMessage() {}

func (x *SendMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMetricResponse.ProtoReflect.Descriptor instead.
func (*SendMetricResponse) Descriptor() ([]byte, []int) {
	return file_proto_metrics_collector_proto_rawDescGZIP(), []int{1}
}

func (x *SendMetricResponse) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *SendMetricResponse) GetServiceUrl() string {
	if x != nil {
		return x.ServiceUrl
	}
	return ""
}

func (x *SendMetricResponse) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *SendMetricResponse) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

var File_proto_metrics_collector_proto protoreflect.FileDescriptor

const file_proto_metrics_collector_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/metrics_collector.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x01\n" +
	"\x11SendMetricRequest\x12\x1f\n" +
	"\vservice_url\x18\x01 \x01(\tR\n" +
	"serviceUrl\x12\x1f\n" +
	"\vmetric_name\x18\x02 \x01(\tR\n" +
	"metricName\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12!\n" +
	"\fmetric_value\x18\x04 \x01(\x01R\vmetricValue\"\xa1\x01\n" +
	"\x12SendMetricResponse\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1f\n" +
	"\vservice_url\x18\x02 \x01(\tR\n" +
	"serviceUrl\x12\x1f\n" +
	"\vmetric_name\x18\x03 \x01(\tR\n" +
	"metricName\x12\x19\n" +
	"\bpod_name\x18\x04 \x01(\tR\apodName2\x91\x01\n" +
	"\x10MetricsCollector\x128\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12C\n" +
	"\n" +
	"SendMetric\x12\x18.proto.SendMetricRequest\x1a\x19.proto.SendMetricResponse\"\x00B\x15Z\x13adapters/grpc/protob\x06proto3"

var (
	file_proto_metrics_collector_proto_rawDescOnce sync.Once
	file_proto_metrics_collector_proto_rawDescData []byte
)

func file_proto_metrics_collector_proto_rawDescGZIP() []byte {
	file_proto_metrics_collector_proto_rawDescOnce.Do(func() {
		file_proto_metrics_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metrics_collector_proto_rawDesc), len(file_proto_metrics_collector_proto_rawDesc)))
	})
	return file_proto_metrics_collector_proto_rawDescData
}

var file_proto_metrics_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_metrics_collector_proto_goTypes = []any{
	(*SendMetricRequest)(nil),     // 0: proto.SendMetricRequest
	(*SendMetricResponse)(nil),    // 1: proto.SendMetricResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
}
var file_proto_metrics_collector_proto_depIdxs = []int32{
	2, // 0: proto.SendMetricResponse.time:type_name -> google.protobuf.Timestamp
	3, // 1: proto.MetricsCollector.Ping:input_type -> google.protobuf.Empty
	0, // 2: proto.MetricsCollector.SendMetric:input_type -> proto.SendMetricRequest
	3, // 3: proto.MetricsCollector.Ping:output_type -> google.protobuf.Empty
	1, // 4: proto.MetricsCollector.SendMetric:output_type -> proto.SendMetricResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_metrics_collector_proto_init() }
func file_proto_metrics_collector_proto_init() {
	if File_proto_metrics_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metrics_collector_proto_rawDesc), len(file_proto_metrics_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metrics_collector_proto_goTypes,
		DependencyIndexes: file_proto_metrics_collector_proto_depIdxs,
		MessageInfos:      file_proto_metrics_collector_proto_msgTypes,
	}.Build()
	File_proto_metrics_collector_proto = out.File
	file_proto_metrics_collector_proto_goTypes = nil
	file_proto_metrics_collector_proto_depIdxs = nil
}
